name: image_classification

services:
  Modified_Resnet:
    build:
      context: .  
      dockerfile: Dockerfile  
    image: img_classifier:latest
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 
    ports:
      - "8080:8080"  
    networks:
      - img_class_net

networks:
  img_class_net:
    driver: bridge